version: "3.8"
services:
  pharmacy-recommendation-redis:
    container_name: pharmacy-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: ohsh0731/pharmacy-recommendation-redis
    ports:
      - "6379:6379"
    